# Generated by Django 3.1.4 on 2021-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0008_auto_20210403_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='homowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phono', models.IntegerField(max_length=10)),
                ('falt', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameModel(
            old_name='flatownerinf',
            new_name='flatownerinfo',
        ),
    ]
