# Generated by Django 3.1.4 on 2021-04-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0009_auto_20210403_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flatownerinfo',
        ),
        migrations.AlterField(
            model_name='homowner',
            name='phono',
            field=models.IntegerField(),
        ),
    ]
