# Generated by Django 3.1.4 on 2021-04-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0010_auto_20210403_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homowner',
        ),
    ]
