# Generated by Django 3.1.4 on 2021-04-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0011_delete_homowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='homowner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phono', models.IntegerField()),
                ('falt', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=254)),
            ],
        ),
    ]
