# Generated by Django 3.1.4 on 2021-04-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0012_homowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homowner',
            name='Type',
            field=models.CharField(choices=[('owner', 'OWNER'), ('tenent', 'TENENT')], default='owner', max_length=10),
        ),
    ]
