# Generated by Django 3.1.4 on 2021-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0014_auto_20210404_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homowner',
            old_name='falt',
            new_name='flat',
        ),
        migrations.AlterField(
            model_name='homowner',
            name='phono',
            field=models.IntegerField(),
        ),
    ]
