# Generated by Django 3.1.4 on 2021-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0015_auto_20210404_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('amount', models.IntegerField(max_length=6)),
                ('tranid', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='homowner',
            name='phono',
            field=models.IntegerField(max_length=12),
        ),
    ]
