# Generated by Django 3.1.4 on 2021-04-04 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0016_auto_20210405_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bildate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('electricity', 'ELECTRICITY'), ('water', 'WATER'), ('cleaning', 'CLEANING'), ('lift', 'LIFT'), ('security', 'SECURITY')], default='electricity', max_length=20),
        ),
    ]
