# Generated by Django 3.1.4 on 2021-04-05 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0017_auto_20210405_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeof', models.CharField(choices=[('electricity', 'ELECTRICITY'), ('water', 'WATER'), ('cleaning', 'CLEANING'), ('lift', 'LIFT'), ('security', 'SECURITY')], default='electricity', max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(max_length=6)),
                ('tranid', models.CharField(max_length=20)),
                ('bildate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
