# Generated by Django 3.1.4 on 2021-04-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0018_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='payer',
        ),
    ]
