# Generated by Django 3.1.4 on 2021-04-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0019_auto_20210406_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='typeof',
            new_name='typeo',
        ),
    ]
