# Generated by Django 3.1.4 on 2021-04-06 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0020_auto_20210406_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='compaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=100)),
                ('dt', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
