# Generated by Django 3.1.4 on 2021-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0021_compaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaint',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
