# Generated by Django 3.1.4 on 2021-04-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0022_auto_20210407_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaint',
            old_name='user',
            new_name='apuser',
        ),
    ]
