# Generated by Django 3.1.4 on 2021-04-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0023_auto_20210407_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaint',
            old_name='status',
            new_name='stat',
        ),
    ]
