# Generated by Django 3.1.4 on 2021-04-09 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0024_auto_20210407_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaint',
            old_name='apuser',
            new_name='uid',
        ),
    ]
