# Generated by Django 3.1.4 on 2021-04-29 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0025_auto_20210410_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='homowndet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatNo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField(default=datetime.date.today)),
                ('occupation', models.CharField(max_length=20)),
                ('comm_address', models.CharField(max_length=100)),
                ('perm_address', models.CharField(max_length=100)),
            ],
        ),
    ]
