# Generated by Django 3.1.4 on 2021-05-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0026_homowndet'),
    ]

    operations = [
        migrations.AddField(
            model_name='homowndet',
            name='CommAddProof',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='homowndet',
            name='PermAddProof',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='homowndet',
            name='SaleDeed',
            field=models.FileField(default='null', upload_to=''),
        ),
        migrations.AddField(
            model_name='homowndet',
            name='idproof',
            field=models.FileField(default='null', upload_to=''),
        ),
    ]
