# Generated by Django 3.1.4 on 2021-05-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0032_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.DateField(default=datetime.date.today)),
                ('trans', models.CharField(max_length=10)),
                ('amount', models.IntegerField(max_length=10)),
            ],
        ),
    ]
