# Generated by Django 3.1.4 on 2021-05-07 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0033_maint'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='regMonth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
