# Generated by Django 3.1.4 on 2021-05-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0034_apartment_regmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='regMonth',
            field=models.CharField(max_length=10),
        ),
    ]
