# Generated by Django 3.1.4 on 2021-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0035_auto_20210508_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='maint',
            name='usid',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
