# Generated by Django 3.1.4 on 2021-08-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0036_maint_usid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaint',
            name='stat',
        ),
    ]
