# Generated by Django 3.1.4 on 2021-08-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0037_remove_compaint_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='compaint',
        ),
    ]
