# Generated by Django 3.1.4 on 2021-08-07 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0038_delete_compaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='compaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=100)),
                ('dt', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
