from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('', landing, name="landingpage"),
    # path('',home,name='homePage'),
    path('login/', loginView, name='loginPage'),
    path('register/', register, name='registerPage'),
    path('logout/', logoutView, name='logoutPage'),

    path('Welcome/', Welcome, name='Welcomepage'),
    path('duespayment/', duespayment, name="duespage"),
    path('complaint/', Addcomplaint, name="complaintpage"),
    #path('complaint/', compt, name="comptpage"),
    path('payment/', payment, name="paymentpage"),
    path('incexp/', viewIncomeExpenditure, name="incexppage"),
    path('approve/', aprove, name="approvepage"),
    path('secretory/', secret, name="scretarypage"),
    path('userprof/', userprof, name="userprofpage"),
    path('financestat/', financialStatus, name="financestatpage"),
    path('Sviewcomp/', Sviewcomp, name="Sviewcomppage"),
    path('viewmain/', viewMaintenance, name="viewmainpage"),
    path('viewmain/', viewmain, name="viewmainpage"),
    path('viewmain/', viewmain, name="viewmainpa"),
    path('viewmaint/', viewmaintain, name="viewmainp"),
    path('viewcomp/', viewcomp, name="viewcomppage"),
    path('createnot/', createNot, name="createnotpage"),
    path('president/', presi, name="presidentpage"),
    path('flatowninfo/', flatowninfo, name="flatownpage"),
    path('financeinfo/', financial, name="financepage"),
    path('financeinfo/', financial, name="financepage"),
    path('flatowninf/', flatin, name="flatowpage"),
    path('appnotice/', apprnoti, name="appNoticepage"),
    path('homeowner', homeuser, name="homeownerpage"),
    path('treasure/', treasure, name="treasurepage"),
    path('addreisdents/', Addresd, name='Addresdpage'),
    path('addexoense/', AddExpense, name='Addexpnpage'),
    path('addincomex/', AddIncome, name='Addincomepage'),
    #path('addcomplaint/', Addcomplaint, name='Addcomppage'),
    path('adddetails/', AddDetails, name='Adddetails'),
    path('addapartment/', Apartment, name='Addapartment'),
    path('paymain/', paymain, name='paymaint'),
]
